### ISSUE TITLE
Уточнення по ДЗ  22

### ISSUE THREAD

**Issue by Dexter19** [olhamalykh/olhamalykh#10]
Ц вас все виконано добре, бачу що розумієте матеріал. Єдине хотів надати приклад останнього завдання просто щоб ви побачили як щн можна реалізувати цю задачу.
const headers = document.querySelectorAll('.container header');

for (let i = 0; i < headers.length; i++) {
    
    let html = headers[i].firstElementChild;
    
    let text = html.textContent;
    let currentId = html.getAttribute('id');
    let currentClass = html.getAttribute('class');
    
    let newHtml = "<h"+(i+1)+">"+text+"</h"+(i+1)+">";

    headers[i].innerHTML = newHtml;
    headers[i].firstElementChild.setAttribute('id', currentId);
    headers[i].firstElementChild.setAttribute('class', currentClass);

    console.log(headers[i].firstElementChild.getAttribute('id')); 
    console.log(headers[i].firstElementChild); 
}

const classes = ['first', 'second', 'third', 'fourth'];

for (let i = 0; i < headers.length; i++) {
    let h = document.querySelector('h'+(i+1));
    h.classList.add(classes[i]);        
}

**Comment by olhamalykh** [comment]
Дякую за рекомендацію!
