### ISSUE TITLE
Рекомендації до ДЗ 23

### ISSUE THREAD

**Issue by Dexter19** [olhamalykh/olhamalykh#11]
У вас все чудово. Єдине що я б вам порадив замість засатрілого onclick -  використовувати addEventListener('click', function() {}.
Як приклад остання задача. Ваш код:
for (let i = 0; i < cards.length; i++) {
  const buttonAddToCart = cards[i].querySelector('.add-to-cart');
  buttonAddToCart.onclick = function() {
    const cardTitle = cards[i].querySelector('.card-title');
    console.log(cardTitle.textContent);
  };
};

Як би я рекомендував:
for (let i = 0; i < cards.length; i++) {
  let addToCartButton = cards[i].querySelector('.add-to-cart');
  addToCartButton.addEventListener('click', function() {
    let title = cards[i].querySelector('.card-title').textContent;
    console.log(title);
  });
}

**Comment by olhamalykh** [comment]
Зрозуміла, дуже дякую!
