### ISSUE TITLE
Дрібні правки до ДЗ-5

### ISSUE THREAD

**Issue by Dexter19** [olhamalykh/olhamalykh#3]
Пункт 4 - 

- Припустімо, що розмір шрифту для body встановлено на 16 пікселів. 
- Всередині файла css/main.css визначте властивсть font-size для strong так, щоб всі слова мали однаковий відносний розмір, еквівалентний 25,6 пікселів.

Змініть на 
html {
  font-size: 100%;
}
strong {
  font-size: 1.6rem;
}

---------------------------------------------------------------------

Не побачив у вас 7 пункту імпорту іконок @import url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"); в файл main.css персонального сайту.

**Comment by olhamalykh** [comment]
Виправила
