### ISSUE TITLE
ДЗ-6

### ISSUE THREAD

**Issue by Dexter19** [olhamalykh/olhamalykh#4]
Пункт 12 - Відредагуйте файл css/common.css
Має бути так 
	:root {
      --main-color: #009;
      --anchor-color: #333;
      --anchor-active-color: salmon;
		--primary-text-color: #000;
		--primary-bg-color: #fff;
		--primary-font-family: 'Roboto', sans-serif; 
		--primary-font-size: 0.875rem / 1.4;
	}

Пункт 13 - 
в Стилях пропущено селектор а
ul.categories li {
    color: indigo;
    text-decoration: none;
    font-size: 1.2rem;
}

а має бути 

ul.categories li a {
    color: indigo;
    text-decoration: none;
    font-size: 1.2rem;
}

Також в 

ul.categories li a:hover {
    background-color: lightgray;
}

має бути ще колір

ul.categories li a:hover {
    color: indianred;
    background-color: lightgray;
}

**Comment by olhamalykh** [comment]
Виправила
