### ISSUE TITLE
Правки ДЗ 13

### ISSUE THREAD

**Issue by Dexter19** [olhamalykh/olhamalykh#6]
Визначте змінну під назвою --padding-form в області :root та призначте їй значення за допомогою 
функції calc(). Значення обчислюється шляхом ділення 30 на 16 і множення на 1rem.
У вас  --padding-form: calc(30 / 16 * 1rem);
Беріть додатково де ділення в дужки таким чином: --padding-form: calc((30/16)*1rem);
------------------------------------------------------------------------------------

**Comment by olhamalykh** [comment]
Дякую, виправила
